# Generated by Django 5.0.6 on 2024-06-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everywhere', '0004_user_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='accounts',
            field=models.ManyToManyField(blank=True, through='everywhere.Account_User', to='everywhere.account'),
        ),
    ]
