# Generated by Django 5.0.6 on 2024-06-26 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everywhere', '0005_alter_user_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='joined',
            field=models.DateTimeField(),
        ),
    ]
